# Espanso configuration
# https://espanso.org/docs/configuration/

# The search bar shortcut
search_shortcut: CTRL+SPACE

# Disable notifications (including startup notification)
show_notifications: false
